# Generated by Django 5.2.4 on 2025-11-18 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_fitnessgoals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('walk', 'Walking'), ('run', 'Running'), ('swim', 'Swimming'), ('cycle', 'Cycling'), ('yoga', 'Yoga')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in Minutes')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
