# Generated by Django 5.2.8 on 2025-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_fitnessactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protein', models.FloatField(help_text='Protein per 100g (g)')),
                ('carbs', models.FloatField(help_text='Carbs per 100g (g)')),
                ('fat', models.FloatField(help_text='Fat per 100g (g)')),
                ('calories', models.FloatField(help_text='Calories per 100g (kcal)')),
            ],
        ),
    ]
