# Generated by Django 5.2.4 on 2025-11-19 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_meal_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_weight', models.FloatField(blank=True, null=True)),
                ('end_weight', models.FloatField(blank=True, null=True)),
                ('breakfast_calories', models.FloatField(default=0)),
                ('lunch_calories', models.FloatField(default=0)),
                ('dinner_calories', models.FloatField(default=0)),
                ('snack_calories', models.FloatField(default=0)),
                ('calories_consumed', models.FloatField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('net_calories', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
