# Generated by Django 5.2.8 on 2025-11-21 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessactivity',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
