# Generated by Django 5.2.8 on 2025-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_fitnessactivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoals',
            name='current_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fitnessgoals',
            name='start_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fitnessgoals',
            name='target_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'meal_type', 'food', 'date')},
        ),
    ]
