# Generated by Django 5.2.8 on 2025-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_fitnessgoals_current_weight_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(),
        ),
    ]
